steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/aerolog-web-$SHORT_SHA",
        "-f",
        "./Aerolog.Web/Dockerfile",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/aerolog-web-$SHORT_SHA"]
  - name: node
    args: ["npm", "install"]
    dir: './Aerolog.Web/client-app'
  - name: node
    args: ["npm", "run", "build"]
    dir: './Aerolog.Web/client-app'
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "aerolog",
        "--image",
        "gcr.io/$PROJECT_ID/aerolog-web-$SHORT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--update-env-vars=SPA_PATH=https://storage.cloud.google.com/aerolog-client-app/$SHORT_SHA",
      ]
images:
  - gcr.io/$PROJECT_ID/aerolog-web-$SHORT_SHA
artifacts:
  objects:
    location: "gs://aerolog-client-app/$SHORT_SHA"
    paths: [./Aerolog.Web/client-app/build/*]
