steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/aerolog-web-$BUILD_ID",
        "-f",
        "./Aerolog.Web/Dockerfile",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/aerolog-web-$BUILD_ID"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "aerolog",
        "--image",
        "gcr.io/$PROJECT_ID/aerolog-web-$BUILD_ID",
        "--platform",
        "managed",
      ]
images:
  - gcr.io/$PROJECT_ID/aerolog-web-$BUILD_ID
