steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/aerolog-web-$BUILD_ID",
        "-f",
        "./Aerolog.Web/Dockerfile",
        ".",
      ]
images:
  - gcr.io/$PROJECT_ID/aerolog-web-$BUILD_ID
