steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/aerolog-web-$SHORT_SHA",
        "-f",
        "./Aerolog.Web/Dockerfile.prod",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/aerolog-web-$SHORT_SHA"]
  - name: node
    args: ["npm", "install"]
    dir: "./Aerolog.Web/client-app"
  - name: node
    args: ["npm", "run", "build"]
    env: ["PUBLIC_URL=https://storage.googleapis.com/aerolog-client-app/"]
    dir: "./Aerolog.Web/client-app"
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "aerolog",
        "--image",
        "gcr.io/$PROJECT_ID/aerolog-web-$SHORT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
      ]
images:
  - gcr.io/$PROJECT_ID/aerolog-web-$SHORT_SHA
artifacts:
  objects:
    location: "gs://aerolog-client-app/"
    paths: [./Aerolog.Web/client-app/build/*]
